# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Math Library of various classes snd methods

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
 #     - name: Restore packages
 #       run: msbuild -p:RestorePackagesConfig=true -t:restore
      - name: Build solution
        run: msbuild Computation.sln -t:build -property:Configuration=Release
